# Generated by Django 5.2.7 on 2025-10-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=255)),
                ('messsege', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=25)),
                ('type', models.CharField(choices=[('UC', 'UNIVERSAL CODEBOX'), ('WD', 'WEB DEVELOPER')], max_length=255)),
                ('added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
