# Generated by Django 5.2.7 on 2025-10-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('UC', 'UNIVERSAL CODEBOX'), ('WD', 'WEB DEVELOPER')], max_length=2),
        ),
    ]
