# Generated by Django 5.2.7 on 2025-10-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_email_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('UNIVERSAL CODEBOX', 'UC'), ('WEB DEVELOPER', 'WB')], max_length=20),
        ),
    ]
