# Generated by Django 5.2.7 on 2025-10-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Company_id',
            new_name='company_id',
        ),
    ]
