# Generated by Django 5.2.7 on 2025-10-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_company_id_company_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='messsege',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('UC', 'UNIVERSAL CODEBOX'), ('WB', 'WEB DEVELOPER')], max_length=20),
        ),
    ]
