# Generated by Django 5.2.7 on 2025-10-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_messsege_company_message_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('UNIVERSAL CODEBOX', 'UNIVERSAL CODEBOX'), ('WEB DEVELOPER', 'WEB DEVELOPER')], max_length=100),
        ),
    ]
